services:
  - type: postgres
    name: fintech-ai-insights-db
    plan: free
    databaseName: financeira
    user: finance_user

  - type: web
    name: fintech-ai-insights
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: fintech-ai-insights-db
          property: connectionString